import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import Image from "next/image"

const inter = Inter({ subsets: ["latin"] })
const name = "Your Name"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen p-2 flex flex-col justify-center items-center`}>
        <div>
          <header className="flex flex-col items-center">
            <Link href="/">
              <Image
                priority
                src="/images/profile.jpg"
                className="rounded-full"
                height={108}
                width={108}
                alt=""
              />
            </Link>
            <h2 className="text-2xl">
              <Link href="/" className="text-inherit">
                {name}
              </Link>
            </h2>
          </header>
        </div>
        {children}
      </body>
    </html>
  )
}
